-- =====================================================
-- Animed - Schema inicial (V1)
-- Banco: Oracle
-- =====================================================

-- =====================================================
-- TB_TUTOR
-- =====================================================
CREATE TABLE TB_TUTOR (
    ID_TUTOR        NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME            VARCHAR2(120) NOT NULL,
    EMAIL           VARCHAR2(150) NOT NULL,
    CPF             VARCHAR2(14)  NOT NULL,
    TELEFONE        VARCHAR2(20),
    PONTOS_TOTAIS   NUMBER(10) DEFAULT 0 NOT NULL,
    NIVEL           VARCHAR2(20) DEFAULT 'BASICO' NOT NULL,
    PLANO           VARCHAR2(20) DEFAULT 'GRATUITO' NOT NULL,
    DATA_CADASTRO   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATIVO           NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT UK_TUTOR_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_TUTOR_CPF UNIQUE (CPF),
    CONSTRAINT CK_TUTOR_NIVEL CHECK (NIVEL IN ('BASICO','CUIDADOR','TUTOR_PREMIUM')),
    CONSTRAINT CK_TUTOR_PLANO CHECK (PLANO IN ('GRATUITO','INTERMEDIARIO','PREMIUM')),
    CONSTRAINT CK_TUTOR_ATIVO CHECK (ATIVO IN (0,1))
);

-- =====================================================
-- TB_PET
-- =====================================================
CREATE TABLE TB_PET (
    ID_PET              NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME                VARCHAR2(80) NOT NULL,
    ESPECIE             VARCHAR2(20) NOT NULL,
    RACA                VARCHAR2(80),
    DATA_NASCIMENTO     DATE,
    PESO_KG             NUMBER(5,2),
    CASTRADO            NUMBER(1) DEFAULT 0,
    OBSERVACOES_SAUDE   VARCHAR2(1000),
    ID_TUTOR            NUMBER(19) NOT NULL,
    CONSTRAINT FK_PET_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TB_TUTOR(ID_TUTOR),
    CONSTRAINT CK_PET_ESPECIE CHECK (ESPECIE IN ('CACHORRO','GATO','AVE','ROEDOR','REPTIL','OUTRO'))
);

-- =====================================================
-- TB_PETSHOP
-- =====================================================
CREATE TABLE TB_PETSHOP (
    ID_PETSHOP            NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RAZAO_SOCIAL          VARCHAR2(150) NOT NULL,
    NOME_FANTASIA         VARCHAR2(120) NOT NULL,
    CNPJ                  VARCHAR2(18) NOT NULL,
    ENDERECO              VARCHAR2(250),
    CIDADE                VARCHAR2(100),
    UF                    VARCHAR2(2),
    TELEFONE              VARCHAR2(20),
    TAXA_MENSAL           NUMBER(10,2) DEFAULT 99.90 NOT NULL,
    COMISSAO_PERCENTUAL   NUMBER(5,2) DEFAULT 5.00 NOT NULL,
    ATIVO                 NUMBER(1) DEFAULT 1 NOT NULL,
    DATA_PARCERIA         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_PETSHOP_CNPJ UNIQUE (CNPJ)
);

-- =====================================================
-- TB_VACINA
-- =====================================================
CREATE TABLE TB_VACINA (
    ID_VACINA               NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_VACINA             VARCHAR2(100) NOT NULL,
    DATA_APLICACAO          DATE NOT NULL,
    DATA_PROXIMA_DOSE       DATE,
    VETERINARIO_RESPONSAVEL VARCHAR2(120),
    CLINICA                 VARCHAR2(150),
    LOTE                    VARCHAR2(50),
    OBSERVACOES             VARCHAR2(500),
    ID_PET                  NUMBER(19) NOT NULL,
    CONSTRAINT FK_VACINA_PET FOREIGN KEY (ID_PET) REFERENCES TB_PET(ID_PET)
);

-- =====================================================
-- TB_CONSULTA
-- =====================================================
CREATE TABLE TB_CONSULTA (
    ID_CONSULTA   NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_HORA     TIMESTAMP NOT NULL,
    MOTIVO        VARCHAR2(250) NOT NULL,
    DIAGNOSTICO   VARCHAR2(1000),
    PRESCRICAO    VARCHAR2(1000),
    VALOR         NUMBER(10,2),
    STATUS        VARCHAR2(20) DEFAULT 'AGENDADA' NOT NULL,
    VETERINARIO   VARCHAR2(120),
    ID_PET        NUMBER(19) NOT NULL,
    ID_PETSHOP    NUMBER(19),
    CONSTRAINT FK_CONSULTA_PET FOREIGN KEY (ID_PET) REFERENCES TB_PET(ID_PET),
    CONSTRAINT FK_CONSULTA_PETSHOP FOREIGN KEY (ID_PETSHOP) REFERENCES TB_PETSHOP(ID_PETSHOP),
    CONSTRAINT CK_CONSULTA_STATUS CHECK (STATUS IN ('AGENDADA','REALIZADA','CANCELADA','NAO_COMPARECEU'))
);

-- =====================================================
-- TB_TRANSACAO_PARCEIRO
-- =====================================================
CREATE TABLE TB_TRANSACAO_PARCEIRO (
    ID_TRANSACAO        NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_HORA           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VALOR_BRUTO         NUMBER(10,2) NOT NULL,
    DESCONTO_APLICADO   NUMBER(10,2) DEFAULT 0,
    VALOR_FINAL         NUMBER(10,2) NOT NULL,
    COMISSAO_CLYVO      NUMBER(10,2) NOT NULL,
    PONTOS_GERADOS      NUMBER(10) NOT NULL,
    DESCRICAO_PRODUTO   VARCHAR2(250),
    ID_TUTOR            NUMBER(19) NOT NULL,
    ID_PETSHOP          NUMBER(19) NOT NULL,
    CONSTRAINT FK_TRANSACAO_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TB_TUTOR(ID_TUTOR),
    CONSTRAINT FK_TRANSACAO_PETSHOP FOREIGN KEY (ID_PETSHOP) REFERENCES TB_PETSHOP(ID_PETSHOP)
);

-- =====================================================
-- TB_HISTORICO_PONTUACAO
-- =====================================================
CREATE TABLE TB_HISTORICO_PONTUACAO (
    ID_HISTORICO   NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_ACAO      VARCHAR2(40) NOT NULL,
    PONTOS_GANHOS  NUMBER(10) NOT NULL,
    DESCRICAO      VARCHAR2(250),
    DATA_HORA      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ID_TUTOR       NUMBER(19) NOT NULL,
    CONSTRAINT FK_HIST_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TB_TUTOR(ID_TUTOR)
);

-- =====================================================
-- ÍNDICES (performance em buscas comuns)
-- =====================================================
CREATE INDEX IDX_PET_TUTOR ON TB_PET(ID_TUTOR);
CREATE INDEX IDX_VACINA_PET ON TB_VACINA(ID_PET);
CREATE INDEX IDX_VACINA_DATA ON TB_VACINA(DATA_APLICACAO);
CREATE INDEX IDX_CONSULTA_PET ON TB_CONSULTA(ID_PET);
CREATE INDEX IDX_CONSULTA_DATA ON TB_CONSULTA(DATA_HORA);
CREATE INDEX IDX_TRANSACAO_TUTOR ON TB_TRANSACAO_PARCEIRO(ID_TUTOR);
CREATE INDEX IDX_TRANSACAO_PETSHOP ON TB_TRANSACAO_PARCEIRO(ID_PETSHOP);
CREATE INDEX IDX_HIST_TUTOR ON TB_HISTORICO_PONTUACAO(ID_TUTOR);
CREATE INDEX IDX_TUTOR_PONTOS ON TB_TUTOR(PONTOS_TOTAIS DESC);
