-- =====================================================
-- CLYVO VET - Seed de dados iniciais (V2)
-- Dados de demonstração para o squad e correção FIAP
-- =====================================================

-- TUTORES
INSERT INTO TB_TUTOR (NOME, EMAIL, CPF, TELEFONE, PONTOS_TOTAIS, NIVEL, PLANO)
VALUES ('Marina Oliveira', 'marina.oliveira@email.com', '123.456.789-00', '(11) 98765-4321', 350, 'CUIDADOR', 'INTERMEDIARIO');

INSERT INTO TB_TUTOR (NOME, EMAIL, CPF, TELEFONE, PONTOS_TOTAIS, NIVEL, PLANO)
VALUES ('Carlos Mendes', 'carlos.mendes@email.com', '987.654.321-00', '(11) 91234-5678', 720, 'TUTOR_PREMIUM', 'PREMIUM');

INSERT INTO TB_TUTOR (NOME, EMAIL, CPF, TELEFONE, PONTOS_TOTAIS, NIVEL, PLANO)
VALUES ('Juliana Santos', 'juliana.santos@email.com', '456.789.123-00', '(11) 99876-5432', 50, 'BASICO', 'GRATUITO');

-- PET SHOPS PARCEIROS
INSERT INTO TB_PETSHOP (RAZAO_SOCIAL, NOME_FANTASIA, CNPJ, ENDERECO, CIDADE, UF, TELEFONE, TAXA_MENSAL, COMISSAO_PERCENTUAL)
VALUES ('Mundo Pet Comércio Ltda', 'Mundo Pet', '12.345.678/0001-99', 'Av. Paulista, 1500', 'São Paulo', 'SP', '(11) 3333-4444', 99.90, 5.00);

INSERT INTO TB_PETSHOP (RAZAO_SOCIAL, NOME_FANTASIA, CNPJ, ENDERECO, CIDADE, UF, TELEFONE, TAXA_MENSAL, COMISSAO_PERCENTUAL)
VALUES ('Cobasi Animais e Plantas', 'Cobasi Vila Mariana', '98.765.432/0001-11', 'Rua Domingos de Morais, 800', 'São Paulo', 'SP', '(11) 4444-5555', 199.90, 7.00);

-- PETS
INSERT INTO TB_PET (NOME, ESPECIE, RACA, DATA_NASCIMENTO, PESO_KG, CASTRADO, OBSERVACOES_SAUDE, ID_TUTOR)
VALUES ('Thor', 'CACHORRO', 'Golden Retriever', DATE '2020-03-15', 32.5, 1, 'Saudável, sem alergias conhecidas', 1);

INSERT INTO TB_PET (NOME, ESPECIE, RACA, DATA_NASCIMENTO, PESO_KG, CASTRADO, OBSERVACOES_SAUDE, ID_TUTOR)
VALUES ('Mia', 'GATO', 'Persa', DATE '2021-07-20', 4.2, 1, 'Histórico de cistite, dieta especial', 1);

INSERT INTO TB_PET (NOME, ESPECIE, RACA, DATA_NASCIMENTO, PESO_KG, CASTRADO, OBSERVACOES_SAUDE, ID_TUTOR)
VALUES ('Rex', 'CACHORRO', 'Pastor Alemão', DATE '2018-11-10', 38.0, 1, 'Displasia coxofemoral leve', 2);

INSERT INTO TB_PET (NOME, ESPECIE, RACA, DATA_NASCIMENTO, PESO_KG, CASTRADO, OBSERVACOES_SAUDE, ID_TUTOR)
VALUES ('Luna', 'GATO', 'SRD', DATE '2023-01-05', 3.8, 0, 'Filhote adotada de ONG', 3);

-- VACINAS
INSERT INTO TB_VACINA (NOME_VACINA, DATA_APLICACAO, DATA_PROXIMA_DOSE, VETERINARIO_RESPONSAVEL, CLINICA, LOTE, ID_PET)
VALUES ('V10 (Polivalente Canina)', DATE '2024-03-15', DATE '2025-03-15', 'Dra. Patrícia Lima', 'Clínica VetCare', 'BTH2024-589', 1);

INSERT INTO TB_VACINA (NOME_VACINA, DATA_APLICACAO, DATA_PROXIMA_DOSE, VETERINARIO_RESPONSAVEL, CLINICA, LOTE, ID_PET)
VALUES ('Antirrábica', DATE '2024-04-20', DATE '2025-04-20', 'Dr. Roberto Silva', 'Clínica VetCare', 'AR2024-301', 1);

INSERT INTO TB_VACINA (NOME_VACINA, DATA_APLICACAO, DATA_PROXIMA_DOSE, VETERINARIO_RESPONSAVEL, CLINICA, LOTE, ID_PET)
VALUES ('V4 (Quádrupla Felina)', DATE '2024-05-10', DATE '2025-05-10', 'Dra. Patrícia Lima', 'Clínica VetCare', 'V4-2024-122', 2);

-- CONSULTAS
INSERT INTO TB_CONSULTA (DATA_HORA, MOTIVO, DIAGNOSTICO, VALOR, STATUS, VETERINARIO, ID_PET, ID_PETSHOP)
VALUES (TIMESTAMP '2024-09-15 14:30:00', 'Check-up anual', 'Animal saudável, todos parâmetros normais', 280.00, 'REALIZADA', 'Dra. Patrícia Lima', 1, 1);

INSERT INTO TB_CONSULTA (DATA_HORA, MOTIVO, VALOR, STATUS, VETERINARIO, ID_PET, ID_PETSHOP)
VALUES (TIMESTAMP '2025-06-10 10:00:00', 'Consulta de retorno', 180.00, 'AGENDADA', 'Dra. Patrícia Lima', 2, 1);

-- TRANSAÇÕES (compras em pet shops)
INSERT INTO TB_TRANSACAO_PARCEIRO (VALOR_BRUTO, DESCONTO_APLICADO, VALOR_FINAL, COMISSAO_CLYVO, PONTOS_GERADOS, DESCRICAO_PRODUTO, ID_TUTOR, ID_PETSHOP)
VALUES (150.00, 7.50, 142.50, 7.13, 14, 'Ração Premier Golden 15kg', 1, 1);

INSERT INTO TB_TRANSACAO_PARCEIRO (VALOR_BRUTO, DESCONTO_APLICADO, VALOR_FINAL, COMISSAO_CLYVO, PONTOS_GERADOS, DESCRICAO_PRODUTO, ID_TUTOR, ID_PETSHOP)
VALUES (89.90, 13.49, 76.41, 5.35, 7, 'Antipulgas Bravecto', 2, 2);

-- HISTÓRICO DE PONTUAÇÃO
INSERT INTO TB_HISTORICO_PONTUACAO (TIPO_ACAO, PONTOS_GANHOS, DESCRICAO, ID_TUTOR)
VALUES ('CADASTRO_PET', 50, 'Cadastro do pet Thor', 1);

INSERT INTO TB_HISTORICO_PONTUACAO (TIPO_ACAO, PONTOS_GANHOS, DESCRICAO, ID_TUTOR)
VALUES ('PERFIL_COMPLETO', 100, 'Perfil completo do pet Thor', 1);

INSERT INTO TB_HISTORICO_PONTUACAO (TIPO_ACAO, PONTOS_GANHOS, DESCRICAO, ID_TUTOR)
VALUES ('REGISTRO_VACINA', 30, 'Vacinação: V10 - Thor', 1);

INSERT INTO TB_HISTORICO_PONTUACAO (TIPO_ACAO, PONTOS_GANHOS, DESCRICAO, ID_TUTOR)
VALUES ('CHECKUP_REALIZADO', 60, 'Check-up realizado em Thor', 1);

COMMIT;
